### ISSUE TITLE
Inject variables not correctly evaluated

### ISSUE THREAD

**Issue by markdebont** [valenssoftware/bamboo-dynamicplans-plugin#2]
When using Bamboo's (5.9.1) "Inject Bamboo variables configuration" to inject variables from a property file I can not evaluate the variables correctly.

Example (copy from the log):

30-Sep-2015 13:18:43 	GroovyShell bindings:
30-Sep-2015 13:18:43 	    groovyVariableName=Condition
30-Sep-2015 13:18:43 	    inject.FW_S2L=6.20

Then I try to evaluate:

return inject.FW_S2L[1]=='6.20'

I get: (copy from the log):

30-Sep-2015 13:18:43 	Groovy Shell starting
30-Sep-2015 13:18:43 	Groovy script return inject.FW_S2L[1]=='6.20' evaluated to [null]
30-Sep-2015 13:18:43 	Disabling task [SKIPME]

Instead of TRUE/FALSE

cc @giulio1979

**Comment by af6140** [comment]
Having the same issue.

**Comment by af6140** [comment]
Try to work around as this.'inject.FW_S2L' and has no vail.

**Comment by af6140** [comment]
Figured out a work around, use this.'inject.FW_S2L[1]' should work.

**Comment by markdebont** [comment]
Thanks, using ' ' made it working!
