### ISSUE TITLE
Variable scripting example does not work

### ISSUE THREAD

**Issue by bentolor** [valenssoftware/bamboo-dynamicplans-plugin#3]
The example variable scripting obviously does not work.

     script:  if (repository_git_branch_0.equalsIgnoreCase("master")) return "publish" else return "preview"; 

Evaluates for a branch plan as follows:

````
07-Dez-2015 16:34:09 	GroovyShell bindings:
07-Dez-2015 16:34:09 	    groovyVariableName=sonar_analysis_mode
07-Dez-2015 16:34:09 	    bambooDelimiterParsingDisabled_0=true
07-Dez-2015 16:34:09 	    filter_pattern_option_0=none
07-Dez-2015 16:34:09 	    filter_pattern_regex_0=
07-Dez-2015 16:34:09 	    changeset_filter_pattern_regex_0=
07-Dez-2015 16:34:09 	    repository_common_quietPeriod_enabled_0=false
07-Dez-2015 16:34:09 	    repository_common_quietPeriod_period_0=10
07-Dez-2015 16:34:09 	    repository_common_quietPeriod_maxRetries_0=5
07-Dez-2015 16:34:09 	    repository_git_repositoryUrl_0=xxx
07-Dez-2015 16:34:09 	    repository_git_branch_0=master
07-Dez-2015 16:34:09 	    repository_git_useShallowClones_0=true
07-Dez-2015 16:34:09 	    repository_git_useRemoteAgentCache_0=false
07-Dez-2015 16:34:09 	    repository_git_useSubmodules_0=false
07-Dez-2015 16:34:09 	    repository_git_commandTimeout_0=180
07-Dez-2015 16:34:09 	    repository_git_verbose_logs_0=false
07-Dez-2015 16:34:09 	    repository_git_fetch_whole_repository_0=false
07-Dez-2015 16:34:09 	    repository_git_sharedCrendentials_0=103120897
07-Dez-2015 16:34:09 	    repository_git_authenticationType_0=SHARED_CREDENTIALS
07-Dez-2015 16:34:09 	    selectedWebRepositoryViewer_0=bamboo.webrepositoryviewer.provided:noRepositoryViewer
07-Dez-2015 16:34:09 	Groovy Shell starting
07-Dez-2015 16:34:09 	Groovy script  if (repository_git_branch_0.equalsIgnoreCase("master")) return "publish" else return "preview"; evaluated to [publish]
````

While the bamboo variables are fine:

````
Beginning to execute external process for build '...'
..
bamboo_repository_git_branch=test/bamboo-trigger
````

Obivously the example is looking on the wrong variables and I have no clue how to access the regular Bamboo variables inside the Groovy scrioting

**Comment by giulio1979** [comment]
according to the sample you provided 07-Dez-2015 16:34:09        repository_git_branch_0=master

should evaluate to publish ... return "publish" else return "preview"; evaluated to [publish]

not sure if I understand the question here ...

**Comment by bentolor** [comment]
I'm referring to the example posted in the `README.md`.

My report illustrates, that
- The script is executed in a branch which becomes reflects in the Bamboo-Variable `bamboo_repository_git_branch` has the value `test/bamboo-trigger` (the actual branch name)
- The reference example  in the `README.md` does not work as intended, because it always looks into the variable `repository_git_branch_0` which **is always** ` master` even for branch plans .

I'm wondering how to access & use the bamboo variable `bamboo_repository_git_branch` which contain the actual branch name. The non-working example in the `README.md` should be adjusted accordingly.

**Comment by giulio1979** [comment]
let me try to add more variables from task context and we see how it goes

**Comment by bentolor** [comment]
This would be great!

**Comment by giulio1979** [comment]
I pushed and released new version, I tried adding all variables possible

**Comment by bentolor** [comment]
Thank you. I just updated & tried again.

Unfortunately I do not see any additional Bamboo variables becoming visible. Maybe Bamboo sets the `bamboo_repository_git_branch` variable only _after_ the checkout task and hence after the script evaluation occurs.

Did the examples in the README work for you? I'm on Bamboo 5.9.4

    if (repository_git_branch_0.equalsIgnoreCase("develop")) return "develop";

**Comment by giulio1979** [comment]
You should see in your build log something like this:

GroovyShell bindings: 
simple	18-Feb-2016 00:08:40	    groovyVariableName=TASKS_DISABLE_PER_BRANCH
simple	18-Feb-2016 00:08:40	    DISABLE_UNUSED_PACKAGES=|NoPackagesDoDisable
simple	18-Feb-2016 00:08:40	    GRADLE_OPTS=
simple	18-Feb-2016 00:08:40	    DISABLE_VNC_SERVER_TASKS=|.* VNC .*
simple	18-Feb-2016 00:08:40	    JAVA_SOURCE=source
simple	18-Feb-2016 00:08:40	    hosts=
simple	18-Feb-2016 00:08:40	    extravars=
simple	18-Feb-2016 00:08:40	    MAVEN_DEFAULT_TARGET=clean javadoc:jar install
simple	18-Feb-2016 00:08:40	    inventory=aws_useast_dcollqa
simple	18-Feb-2016 00:08:40	    POM_FILE_NAME=pom.xml
simple	18-Feb-2016 00:08:40	    MAVEN_OPTS=-U
simple	18-Feb-2016 00:08:40	    SourcePath=source
simple	18-Feb-2016 00:08:40	    ANSIBLE_COMMON_ARGS=--vault-password-file ~/ansible-vault-pass -v
simple	18-Feb-2016 00:08:40	    GRADLE_SOURCE=source
simple	18-Feb-2016 00:08:40	    DISABLE_MONGO_TASKS_MASK=|.*Mongo.*
simple	18-Feb-2016 00:08:40	    SOURCE=source
simple	18-Feb-2016 00:08:40	    TASKS_DISABLE_PER_BRANCH=script:     def mask=".*master.*|.*develop.*"; try{ if (repository_git_branch_0.equalsIgnoreCase("master")) mask=".*develop.*|.*feature.*";   if (repository_git_branch_0.equalsIgnoreCase("develop") || repository_git_branch_0.equalsIgnoreCase("feature.*integrated.*")) mask=".*master.*|.*feature.*"; }catch(Throwable e){}; try{  if (repository_stash_branch_0.equalsIgnoreCase("master")) mask=".*develop.*|.*feature.*";   if (repository_stash_branch_0.equalsIgnoreCase("develop") || repository_stash_branch_0.equalsIgnoreCase("feature.*integrated.*")) mask=".*master.*|.*feature.*"; }catch(Throwable e){}; return mask;
simple	18-Feb-2016 00:08:40	    playbook=util_allegro_upload.yml
simple	18-Feb-2016 00:08:40	    bambooDelimiterParsingDisabled_0=true
simple	18-Feb-2016 00:08:40	    filter_pattern_option_0=none
simple	18-Feb-2016 00:08:40	    filter_pattern_regex_0=
simple	18-Feb-2016 00:08:40	    changeset_filter_pattern_regex_0=
simple	18-Feb-2016 00:08:40	    repository_common_quietPeriod_enabled_0=false
simple	18-Feb-2016 00:08:40	    repository_common_quietPeriod_period_0=10
simple	18-Feb-2016 00:08:40	    repository_common_quietPeriod_maxRetries_0=5
simple	18-Feb-2016 00:08:40	    repository_git_branch_0=develop
simple	18-Feb-2016 00:08:40	    repository_git_useShallowClones_0=false
simple	18-Feb-2016 00:08:40	    repository_git_useRemoteAgentCache_0=false
simple	18-Feb-2016 00:08:40	    repository_git_useSubmodules_0=false
simple	18-Feb-2016 00:08:40	    repository_git_commandTimeout_0=180
simple	18-Feb-2016 00:08:40	    repository_git_verbose_logs_0=false
simple	18-Feb-2016 00:08:40	    repository_git_fetch_whole_repository_0=true
simple	18-Feb-2016 00:08:40	    repository_git_ssh_passphrase_0=
simple	18-Feb-2016 00:08:40	    repository_git_username_0=
simple	18-Feb-2016 00:08:40	    repository_git_authenticationType_0=
simple	18-Feb-2016 00:08:40	Groovy Shell starting
simple	18-Feb-2016 00:08:40	Groovy script      def mask=".*master.*|.*develop.*"; try{ if (repository_git_branch_0.equalsIgnoreCase("master")) mask=".*develop.*|.*feature.*";   if (repository_git_branch_0.equalsIgnoreCase("develop") || repository_git_branch_0.equalsIgnoreCase("feature.*integrated.*")) mask=".*master.*|.*feature.*"; }catch(Throwable e){}; try{  if (repository_stash_branch_0.equalsIgnoreCase("master")) mask=".*develop.*|.*feature.*";   if (repository_stash_branch_0.equalsIgnoreCase("develop") || repository_stash_branch_0.equalsIgnoreCase("feature.*integrated.*")) mask=".*master.*|.*feature.*"; }catch(Throwable e){}; return mask; evaluated to [.*master.*|.*feature.*]

**Comment by giulio1979** [comment]
the package for logging in case you would like to increase logging level is org.valens.

**Comment by bentolor** [comment]
Thanks for your fast feedback.

Hmmm.... Your output does not contain `bamboo_repository_git_branch` either.

In my original issue you can see, that the script does actually see a `repository_git_branch_0=master`: I think this is the configured repository for the *main plan.* I only start to see the branch name for the branches created by Bamboos [Automatic branch management](https://confluence.atlassian.com/bamboo/using-plan-branches-289276872.html#Usingplanbranches-Automaticbranchmanagement) after the checkout task in the environment variables.

Do you use Automatic branch management?

**Comment by giulio1979** [comment]
Yup, I use automatic branch management on most of my plans.
