### ISSUE TITLE
Question on format of regular expresson in order to disable tasks

### ISSUE THREAD

**Issue by markdebont** [valenssoftware/bamboo-dynamicplans-plugin#5]
I've used the string "SKIPME" in the Task Matcher field to skip tasks. And this works fine. 
I want to use something like SKIPME* or SKIPME$ , /SKIPME$/ to still be using the description field. But this does not seems to function.

Is there a particular regex format I need to use?

**Comment by giulio1979** [comment]
I use this for example:

script:     def mask=".*master.*|.*develop.*"; try{ if (repository_git_branch_0.equalsIgnoreCase("master")) mask=".*develop.*|.*feature.*";   if (repository_git_branch_0.equalsIgnoreCase("develop") || repository_git_branch_0.equalsIgnoreCase("feature.*integrated.*")) mask=".*master.*|.*feature.*"; }catch(Throwable e){}; try{  if (repository_stash_branch_0.equalsIgnoreCase("master")) mask=".*develop.*|.*feature.*";   if (repository_stash_branch_0.equalsIgnoreCase("develop") || repository_stash_branch_0.equalsIgnoreCase("feature.*integrated.*")) mask=".*master.*|.*feature.*"; }catch(Throwable e){}; return mask;


It would return something like: .*master.*|.*feature.*

And I name my tasks:

Task for master branch
Task for develop branch
Task for features branch
