### ISSUE TITLE
Refactoring Code

### ISSUE THREAD

**Issue by CoyoteWAN** [valenssoftware/bamboo-dynamicplans-plugin#7]
I created a refactor about a month or two ago.  I was wondering if you anyone was interested in me dropping it in the public repo.  I did a lot of updates to make it compliant with the latest API or at least it was at the time, Bamboo 5.10.1.1.  Is there any suggestions on how I would go about uploading those changes?  Never used GitHub for uploading before, so I figured I would ask first.

**Comment by giulio1979** [comment]
Hi, you need to make a pull request if you want me to incorporate your changes.
